---

- hosts: 
    - hacc-build
    - alveo-u250
    - alveo-u280
    - alveo-u50d
    - alveo-u55c
    - versal-vck5000
    - hacc-boxes
    #- alveo-u55c-01.inf.ethz.ch
    #- alveo-u55c-02.inf.ethz.ch
  become: true
  become_method: community.general.sudosu
  become_user: root
  ignore_unreachable: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
  #vars_files: vars.yml  
  tasks:
    - include_tasks: ./tasks/cli-templates-install.yml