---

- hosts:
    #- hacc-build
    #- alveo-u250
    #- alveo-u280
    #- alveo-u50d
    #- alveo-u55c
    #- versal-vck5000
    #- hacc-boxes
    #- alveo-u55c-01.inf.ethz.ch
    - hacc-box-01.inf.ethz.ch
  become: true
  become_method: community.general.sudosu
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
    constants: false
    common: false
    coyote: false
    enable: false
    examine: false
    get: false
    hip: false
    mpi: true
    program: false
    reboot: false
    run: false
    set: false
    sgutil: false
    templates: false
    validate: false
    vitis: false
  tasks:
    #always
    #- name: copy program/vivado
    #  copy:
    #    src: "../cli/program/vivado.sh"
    #    dest: /opt/cli/program/vivado
    #    mode: 0755
    #- name: remove constants/CLI_PATH
    #  ansible.builtin.file:
    #    path: /opt/cli/constants/CLI_PATH
    #    state: absent

    #constants
    - name: copy XILINX_TOOLS_PATH
      copy:
        src: "../cli/constants/XILINX_TOOLS_PATH"
        dest: /opt/cli/constants/XILINX_TOOLS_PATH
        mode: 0644
      when: constants
    - name: copy MPICH_PATH
      copy:
        src: "../cli/constants/MPICH_PATH"
        dest: /opt/cli/constants/MPICH_PATH
        mode: 0644
      when: constants
    - name: copy LOCAL_PATH
      copy:
        src: "../cli/constants/LOCAL_PATH"
        dest: /opt/cli/constants/LOCAL_PATH
        mode: 0644
      when: constants      

    #common
    - name: copy common/get_booking_system_servers_list script
      copy:
        src: "../cli/common/get_booking_system_servers_list.sh"
        dest: /opt/cli/common/get_booking_system_servers_list
        mode: 0755
      when: common
    - name: copy common/project_dialog script
      copy:
        src: "../cli/common/project_dialog.sh"
        dest: /opt/cli/common/project_dialog
        mode: 0755
      when: common
    - name: copy common/ssh_key_add
      copy:
        src: "../cli/common/ssh_key_add.sh"
        dest: /opt/cli/common/ssh_key_add
        mode: 0755
      when: common
    - name: copy common/version_dialog script
      copy:
        src: "../cli/common/version_dialog.sh"
        dest: /opt/cli/common/version_dialog
        mode: 0755
      when: common
    - name: copy common/version_dialog_check script
      copy:
        src: "../cli/common/version_dialog_check.sh"
        dest: /opt/cli/common/version_dialog_check
        mode: 0755
      when: common
    - name: copy common/get_constant
      copy:
        src: "../cli/common/get_constant.sh"
        dest: /opt/cli/common/get_constant
        mode: 0755
      when: common
    - name: copy common/device_dialog_gpu script
      copy:
        src: "../cli/common/device_dialog_gpu.sh"
        dest: /opt/cli/common/device_dialog_gpu
        mode: 0755
      when: common
    - name: copy common/get_files script
      copy:
        src: "../cli/common/get_files.sh"
        dest: /opt/cli/common/get_files
        mode: 0755
      when: common

    #coyote
    - name: copy new/coyote
      copy:
        src: "../cli/new/coyote.sh"
        dest: /opt/cli/new/coyote
        mode: 0755
      when: coyote
    - name: copy build/coyote
      copy:
        src: "../cli/build/coyote.sh"
        dest: /opt/cli/build/coyote
        mode: 0755
      when: coyote
    - name: copy program/coyote
      copy:
        src: "../cli/program/coyote.sh"
        dest: /opt/cli/program/coyote
        mode: 0755
      when: coyote
    - name: copy run/coyote
      copy:
        src: "../cli/run/coyote.sh"
        dest: /opt/cli/run/coyote
        mode: 0755
      when: coyote
    - name: copy validate/coyote
      copy:
        src: "../cli/validate/coyote.sh"
        dest: /opt/cli/validate/coyote
        mode: 0755
      when: coyote
    - name: copy program/vivado
      copy:
        src: "../cli/program/vivado.sh"
        dest: /opt/cli/program/vivado
        mode: 0755
      when: coyote
    - name: copy program/revert
      copy:
        src: "../cli/program/revert.sh"
        dest: /opt/cli/program/revert
        mode: 0755
      when: coyote
    - name: copy program/enable_N_REGIONS
      copy:
        src: "../cli/program/enable_N_REGIONS.sh"
        dest: /opt/cli/program/enable_N_REGIONS
        mode: 0755
      when: coyote
    - name: copy program/enable_regions
      copy:
        src: "../cli/program/enable_regions.sh"
        dest: /opt/cli/program/enable_regions
        mode: 0755
      when: coyote

    #enable
    - name: copy enable/vitis script
      copy:
        src: "../cli/enable/vitis.sh"
        dest: /opt/cli/enable/vitis
        mode: 0755
      when: enable
    - name: copy enable/vivado script
      copy:
        src: "../cli/enable/vivado.sh"
        dest: /opt/cli/enable/vivado
        mode: 0755
      when: enable
    - name: copy enable/xrt script
      copy:
        src: "../cli/enable/xrt.sh"
        dest: /opt/cli/enable/xrt
        mode: 0755
      when: enable
    
    #examine
    - name: copy examine
      copy:
        src: "../cli/examine.sh"
        dest: /opt/cli/examine
        mode: 0755
      when: examine

    #get  
    - name: copy get/bdf
      copy:
        src: "../cli/get/bdf.sh"
        dest: /opt/cli/get/bdf
        mode: 0755
      when: get
    - name: copy get/bus
      copy:
        src: "../cli/get/bus.sh"
        dest: /opt/cli/get/bus
        mode: 0755
      when: get
    - name: copy get/get_fpga_device_param
      copy:
        src: "../cli/get/get_fpga_device_param.sh"
        dest: /opt/cli/get/get_fpga_device_param
        mode: 0755
      when: get
    - name: copy get/get_gpu_device_param
      copy:
        src: "../cli/get/get_gpu_device_param.sh"
        dest: /opt/cli/get/get_gpu_device_param
        mode: 0755
      when: get
    - name: copy get/ifconfig
      copy:
        src: "../cli/get/ifconfig.sh"
        dest: /opt/cli/get/ifconfig
        mode: 0755
      when: get
    - name: copy get/name
      copy:
        src: "../cli/get/name.sh"
        dest: /opt/cli/get/name
        mode: 0755
      when: get
    - name: copy get/network
      copy:
        src: "../cli/get/network.sh"
        dest: /opt/cli/get/network
        mode: 0755
      when: get
    - name: copy get/platform
      copy:
        src: "../cli/get/platform.sh"
        dest: /opt/cli/get/platform
        mode: 0755
      when: get
    - name: copy get/serial
      copy:
        src: "../cli/get/serial.sh"
        dest: /opt/cli/get/serial
        mode: 0755
      when: get
    - name: copy get/workflow
      copy:
        src: "../cli/get/workflow.sh"
        dest: /opt/cli/get/workflow
        mode: 0755
      when: get

    #hip
    - name: copy new/hip
      copy:
        src: "../cli/new/hip.sh"
        dest: /opt/cli/new/hip
        mode: 0755
      when: hip
    - name: copy build/hip
      copy:
        src: "../cli/build/hip.sh"
        dest: /opt/cli/build/hip
        mode: 0755
      when: hip
    - name: copy run/hip
      copy:
        src: "../cli/run/hip.sh"
        dest: /opt/cli/run/hip
        mode: 0755
      when: hip
    - name: copy validate/hip
      copy:
        src: "../cli/validate/hip.sh"
        dest: /opt/cli/validate/hip
        mode: 0755
      when: hip

    #mpi
    - name: copy new/mpi
      copy:
        src: "../cli/new/mpi.sh"
        dest: /opt/cli/new/mpi
        mode: 0755
      when: mpi
    - name: copy build/mpi
      copy:
        src: "../cli/build/mpi.sh"
        dest: /opt/cli/build/mpi
        mode: 0755
      when: mpi
    - name: copy run/mpi
      copy:
        src: "../cli/run/mpi.sh"
        dest: /opt/cli/run/mpi
        mode: 0755
      when: mpi
    - name: copy validate/mpi
      copy:
        src: "../cli/validate/mpi.sh"
        dest: /opt/cli/validate/mpi
        mode: 0755
      when: mpi
    - name: copy set/keys
      copy:
        src: "../cli/set/keys.sh"
        dest: /opt/cli/set/keys
        mode: 0755
      when: mpi
    - name: copy common/ssh_key_add
      copy:
        src: "../cli/common/ssh_key_add.sh"
        dest: /opt/cli/common/ssh_key_add
        mode: 0755
      when: mpi

    #program
    - name: copy program/coyote
      copy:
        src: "../cli/program/coyote.sh"
        dest: /opt/cli/program/coyote
        mode: 0755
      when: program
    - name: copy program/fpga_chmod
      copy:
        src: "../cli/program/fpga_chmod.sh"
        dest: /opt/cli/program/fpga_chmod
        mode: 0755
      when: program
    - name: copy program/enable_N_REGIONS
      copy:
        src: "../cli/program/enable_N_REGIONS.sh"
        dest: /opt/cli/program/enable_N_REGIONS
        mode: 0755
      when: program
    - name: copy program/pci_hot_plug
      copy:
        src: "../cli/program/pci_hot_plug.sh"
        dest: /opt/cli/program/pci_hot_plug
        mode: 0755
      when: program
    - name: copy program/reset
      copy:
        src: "../cli/program/reset.sh"
        dest: /opt/cli/program/reset
        mode: 0755
      when: program
    - name: copy program/revert
      copy:
        src: "../cli/program/revert.sh"
        dest: /opt/cli/program/revert
        mode: 0755
      when: program
    - name: copy program/vitis
      copy:
        src: "../cli/program/vitis.sh"
        dest: /opt/cli/program/vitis
        mode: 0755
      when: program
    - name: copy program/vivado
      copy:
        src: "../cli/program/vivado.sh"
        dest: /opt/cli/program/vivado
        mode: 0755
      when: program
    - name: copy program/enable_regions
      copy:
        src: "../cli/program/enable_regions.sh"
        dest: /opt/cli/program/enable_regions
        mode: 0755
      when: program

    #reboot
    - name: copy reboot
      copy:
        src: "../cli/reboot.sh"
        dest: /opt/cli/reboot
        mode: 0755
      when: reboot

    #run
    - name: copy run/coyote
      copy:
        src: "../cli/run/coyote.sh"
        dest: /opt/cli/run/coyote
        mode: 0755
      when: run
    - name: copy run/vitis
      copy:
        src: "../cli/run/vitis.sh"
        dest: /opt/cli/run/vitis
        mode: 0755
      when: run
    
    #set
    - name: copy set/keys
      copy:
        src: "../cli/set/keys.sh"
        dest: /opt/cli/set/keys
        mode: 0755
      when: set
    - name: copy set/gh
      copy:
        src: "../cli/set/gh.sh"
        dest: /opt/cli/set/gh
        mode: 0755
      when: set

    #sgutil
    - name: copy sgutil
      copy:
        src: "../cli/sgutil.sh"
        dest: /opt/cli/sgutil
        mode: 0755
      when: sgutil
    - name: copy sgutil_completion to /usr/share/bash-completion/completions
      copy:
        src: "../cli/sgutil_completion.sh"
        dest: /usr/share/bash-completion/completions/sgutil
        mode: 0755
      when: sgutil

    #templates
    - name: Copy hip templates
      copy:
        src: "../cli/templates/hip"
        dest: /opt/cli/templates
        mode: 0755
      when: templates and hip
    - name: Copy vitis templates
      copy:
        src: "../cli/templates/vitis"
        dest: /opt/cli/templates
        mode: 0755
      when: templates and vitis

    #validate
    - name: copy validate/coyote
      copy:
        src: "../cli/validate/coyote.sh"
        dest: /opt/cli/validate/coyote
        mode: 0755
      when: validate
    - name: copy validate/iperf
      copy:
        src: "../cli/validate/iperf.sh"
        dest: /opt/cli/validate/iperf
        mode: 0755
      when: validate
    - name: copy validate/vitis
      copy:
        src: "../cli/validate/vitis.sh"
        dest: /opt/cli/validate/vitis
        mode: 0755
      when: validate

    #vitis
    - name: copy new/vitis
      copy:
        src: "../cli/new/vitis.sh"
        dest: /opt/cli/new/vitis
        mode: 0755
      when: vitis
    - name: copy build/vitis
      copy:
        src: "../cli/build/vitis.sh"
        dest: /opt/cli/build/vitis
        mode: 0755
      when: vitis
    - name: copy program/vitis
      copy:
        src: "../cli/program/vitis.sh"
        dest: /opt/cli/program/vitis
        mode: 0755
      when: vitis
    - name: copy run/vitis
      copy:
        src: "../cli/run/vitis.sh"
        dest: /opt/cli/run/vitis
        mode: 0755
      when: vitis
    - name: copy validate/vitis
      copy:
        src: "../cli/validate/vitis.sh"
        dest: /opt/cli/validate/vitis
        mode: 0755
      when: vitis
    - name: copy common/get_booking_system_servers_list script
      copy:
        src: "../cli/common/get_booking_system_servers_list.sh"
        dest: /opt/cli/common/get_booking_system_servers_list
        mode: 0755
      when: vitis