---

- hosts: 
    #- hacc-build
    #- alveo-u250
    #- alveo-u280
    #- alveo-u50d
    #- alveo-u55c
    #- versal-vck5000
    #- hacc-boxes
    #- alveo-u55c-01.inf.ethz.ch
    - hacc-box-01.inf.ethz.ch
  become: true
  become_method: community.general.sudosu
  become_user: root
  ignore_unreachable: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    #paths definition
    sgrt_base_path: /opt/cli #/opt/sgrt
    cli_name: sgutil
    #installation control (all means we attempt to delete all directories, files, and scripts)
    all: false
    common: false
    constants: false
  tasks:

    #deleting sgrt
    - name: deleting sgrt
      file:
        path: "{{ sgrt_base_path }}"
        state: absent
      when: all

    #deleting individual items
    - name: deleting constants
      file:
        path: "{{ sgrt_base_path }}/constants/{{ item }}"
        state: absent
      when: all or constants
      loop:
        - HACC_PATH
    - name: deleting common scripts
      file:
        path: "{{ sgrt_base_path }}/common/{{ item }}"
        state: absent
      when: all or common
      loop:
        - get_server_type

     #deleting from profile.d
    - name: remove from system-wide $PATH.
      file:
        path: "/etc/profile.d/{{ cli_name }}.sh"
        state: absent
      when: all