---

- hosts: 
    #- hacc-build
    #- alveo-u250
    #- alveo-u280
    #- alveo-u50d
    #- alveo-u55c
    #- versal-vck5000
    #- hacc-boxes
    #- alveo-u55c-01.inf.ethz.ch
    - hacc-box-01.inf.ethz.ch
  become: true
  become_method: community.general.sudosu
  become_user: root
  ignore_unreachable: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    #paths definition
    sgrt_base_path: /opt/sgrt #/opt/sgrt
    api_path: "{{ sgrt_base_path }}/api"
    cli_path: "{{ sgrt_base_path }}/cli"
    include_path: "{{ sgrt_base_path }}/include"
    cli_name: sgutil
    #installation control (all means we attempt to create and copy all directories, files, and functions or scripts)
    all: false
    #api installation
    api: true #true
    #cli installation
    #scripts
    build: false
    common: false
    enable: false
    examine: false
    get: false
    new: false
    program: false
    reboot: false
    run: false
    set: false
    sgutil: true
    templates: true #true
    validate: true
    #workflows
    coyote: false
    hip: false
    mpi: false
    vitis: true #true
  tasks:

    #creating directories
    - name: creating directories
      file:
        path: "{{ item }}"
        state: directory
      when: all
      loop:
        #base
        - "{{ sgrt_base_path }}"
        - "{{ sgrt_base_path }}/templates"
        #api
        - "{{ api_path }}"
        - "{{ api_path }}/common"
        - "{{ api_path }}/device"
        - "{{ api_path }}/host"
        #cli  
        - "{{ cli_path }}"
        - "{{ cli_path }}/build"
        - "{{ cli_path }}/common"
        - "{{ cli_path }}/constants"
        - "{{ cli_path }}/enable"
        - "{{ cli_path }}/get"
        - "{{ cli_path }}/new"
        - "{{ cli_path }}/program"
        - "{{ cli_path }}/run"
        - "{{ cli_path }}/set"
        - "{{ cli_path }}/validate"
        #include
        - "{{ include_path }}"

    #api
    - name: copying includes
      copy:
        src: "../api/{{ item }}"
        dest: "{{ api_path }}/{{ item }}"
        mode: "0755"
      when: all or api
      loop:
        - device.hpp
        - host.hpp
    #common    
    - name: copying common functions
      copy:
        src: "../api/common/{{ item }}"
        dest: "{{ api_path }}/common/{{ item }}"
        mode: "0755"
      when: all or api
      loop:
        - sgutil_get.hpp
        - sgutil_get.cpp
    #device    
    - name: copying device functions
      copy:
        src: "../api/device/{{ item }}"
        dest: "{{ api_path }}/device/{{ item }}"
        mode: "0755"
      when: all or api
      loop:
        - device.hpp
    #host
    - name: copying host functions
      copy:
        src: "../api/host/{{ item }}"
        dest: "{{ api_path }}/host/{{ item }}"
        mode: "0755"
      when: all or api
      loop:
        - open.hpp
        - open.cpp
        
    #cli
    #copying files (when all/only if they do not exist on the remote)
    #constants
    - name: checking constants
      find:
        paths: "{{ cli_path }}/constants"
        recurse: no
      register: constants_contents
      when: all
    - name: copying constants (if folder is empty)
      copy:
        src: "../cli/constants/{{ item }}"
        dest: "{{ cli_path }}/constants/{{ item }}"
        mode: "0644"
      when: all and constants_contents.matched == 0
      loop:
        - ACAP_SERVERS_LIST
        - CPU_SERVERS_LIST
        - FPGA_SERVERS_LIST
        - GPU_SERVERS_LIST
        - MPICH_PATH
        - MY_DRIVERS_PATH #replaces my LOCAL_PATH
        - MY_PROJECTS_PATH
        - ROCM_PATH  
        - VIRTUALIZED_SERVERS_LIST
        - VIVADO_DEVICES_MAX
        - XILINX_PLATFORMS_PATH
        - XILINX_TOOLS_PATH
        - XRT_PATH
    #devices
    #devices_acap_fpga
    - name: checking devices_acap_fpga
      stat:
        path: "{{ cli_path }}/devices_acap_fpga"
      register: devices_acap_fpga_stat
      when: all
    - name: copying devices_acap_fpga 
      copy:
        src: "../cli/devices_acap_fpga"
        dest: "{{ cli_path }}/devices_acap_fpga"
        mode: "0644"
      when: all and not devices_acap_fpga_stat.stat.exists
    #devices_gpu
    - name: checking devices_gpu
      stat:
        path: "{{ cli_path }}/devices_gpu"
      register: devices_gpu_stat
      when: all
    - name: copying devices_gpu 
      copy:
        src: "../cli/devices_gpu"
        dest: "{{ cli_path }}/devices_gpu"
        mode: "0644"
      when: all and not devices_gpu_stat.stat.exists
    #version
    - name: checking version
      stat:
        path: "{{ sgrt_base_path }}/VERSION"
      register: version_stat
      when: all
    - name: copying version
      copy:
        src: "../VERSION"
        dest: "{{ sgrt_base_path }}/VERSION"
        mode: "0644"
      when: all and not version_stat.stat.exists

    #copying templates
    #coyote
    - name: managing coyote template
      block:
        - name: managing coyote template
          debug:
            msg: ""
        - name: deleting coyote template
          file:
            path: "{{ sgrt_base_path }}/templates/coyote"
            state: absent
          register: coyote_templates
        - name: copying coyote template
          copy:
            src: "../templates/coyote"
            dest: "{{ sgrt_base_path }}/templates"
            mode: "0755"
      when: all or (templates and coyote)
    #hip
    - name: managing hip template
      block:
        - name: managing hip template
          debug:
            msg: ""
        - name: deleting hip template
          file:
            path: "{{ sgrt_base_path }}/templates/hip"
            state: absent
          register: hip_templates
        - name: copying hip template
          copy:
            src: "../templates/hip"
            dest: "{{ sgrt_base_path }}/templates"
            mode: "0755"
      when: all or (templates and hip)
    #mpi
    - name: managing mpi template
      block:
        - name: managing mpi template
          debug:
            msg: ""
        - name: deleting mpi template
          file:
            path: "{{ sgrt_base_path }}/templates/mpi"
            state: absent
          register: mpi_templates
        - name: copying mpi template
          copy:
            src: "../templates/mpi"
            dest: "{{ sgrt_base_path }}/templates"
            mode: "0755"
      when: all or (templates and mpi)
    #vitis  
    - name: managing vitis template
      block:
        - name: managing vitis template
          debug:
            msg: ""
        - name: deleting vitis template
          file:
            path: "{{ sgrt_base_path }}/templates/vitis"
            state: absent
          register: vitis_templates
        - name: copying vitis template
          copy:
            src: "../templates/vitis"
            dest: "{{ sgrt_base_path }}/templates"
            mode: "0755"
      when: all or (templates and vitis)

    #copying scripts 
    #build
    - name: copying build scripts
      copy:
        src: "../cli/build/{{ item }}.sh"
        dest: "{{ cli_path }}/build/{{ item }}"
        mode: "0755"
      when: all or build
      loop:
        - coyote
        - hip
        - mpi
        - vitis
    #common
    - name: copying common scripts
      copy:
        src: "../cli/common/{{ item }}.sh"
        dest: "{{ cli_path }}/common/{{ item }}"
        mode: "0755"
      when: all or common
      loop:
        - bitstream_dialog_check
        - deployment_dialog
        - deployment_dialog_check
        - device_dialog
        - device_dialog_check
        - device_dialog_gpu
        - device_list_check
        - driver_dialog_check
        - get_constant
        - get_email
        - get_files
        - get_multiple_devices
        - get_servers
        - get_vivado_devices
        - is_acap
        - is_cpu
        - is_fpga
        - is_gpu
        - is_member
        - is_virtualized
        - platform_dialog
        - platform_dialog_check
        - project_dialog
        - project_dialog_check
        - ssh_key_add
        - target_dialog
        - target_dialog_check
        - version_dialog
        - version_dialog_check
    #enable
    - name: copying enable scripts
      copy:
        src: "../cli/enable/{{ item }}.sh"
        dest: "{{ cli_path }}/enable/{{ item }}"
        mode: "0755"
      when: all or enable
      loop:
        - vitis
        - vivado
        - xrt
    #examine
    - name: copying examine
      copy:
        src: "../cli/examine.sh"
        dest: "{{ cli_path }}/examine"
        mode: "0755"
      when: all or examine
    #get
    - name: copying get scripts
      copy:
        src: "../cli/get/{{ item }}.sh"
        dest: "{{ cli_path }}/get/{{ item }}"
        mode: "0755"
      when: all or get
      loop:
        - bdf
        - bus 
        - get_fpga_device_param
        - get_gpu_device_param
        - ifconfig
        - name
        - network
        - platform
        - serial
        - servers
        - workflow
    #new
    - name: copying new scripts
      copy:
        src: "../cli/new/{{ item }}.sh"
        dest: "{{ cli_path }}/new/{{ item }}"
        mode: "0755"
      when: all or new
      loop:
        - coyote
        - hip
        - mpi
        - vitis
    #program
    - name: copying program scripts
      copy:
        src: "../cli/program/{{ item }}.sh"
        dest: "{{ cli_path }}/program/{{ item }}"
        mode: "0755"
      when: all or program
      loop:
        - coyote
        - enable_N_REGIONS
        - enable_regions
        - fpga_chmod
        - pci_hot_plug
        - reset
        - revert
        - vitis
        - vivado
    - name: copying program tcl
      copy:
        src: "../cli/program/{{ item }}"
        dest: "{{ cli_path }}/program/{{ item }}"
        mode: "0755"
      when: all or program
      loop:
        - flash_bitstream.tcl
        - flash_xrt_bitstream.tcl
    #reboot
    - name: copying reboot
      copy:
        src: "../cli/reboot.sh"
        dest: "{{ cli_path }}/reboot"
        mode: "0755"
      when: all or reboot
    #run
    - name: copying run scripts
      copy:
        src: "../cli/run/{{ item }}.sh"
        dest: "{{ cli_path }}/run/{{ item }}"
        mode: "0755"
      when: all or run
      loop:
        - coyote
        - hip
        - mpi
        - vitis
    #set
    - name: copying set scripts
      copy:
        src: "../cli/set/{{ item }}.sh"
        dest: "{{ cli_path }}/set/{{ item }}"
        mode: "0755"
      when: all or set
      loop:
        - gh
        - keys
    #sgutil
    - name: managing sgutil
      block:
        - name: managing sgutil
          debug:
            msg: ""
        - name: copying sgutil
          copy:
            src: "../cli/{{ cli_name }}.sh"
            dest: "{{ cli_path }}/{{ cli_name }}"
            mode: 0755
          register: sgutil_copy
        - name: adding to profile.d (system-wide $PATH)
          copy:
            dest: "/etc/profile.d/{{ cli_name }}.sh" #cli.sh
            content: 'PATH=$PATH:{{ cli_path }}'
        - name: copying sgutil_completion
          copy:
            src: "../cli/{{ cli_name }}_completion.sh"
            dest: /usr/share/bash-completion/completions/{{ cli_name }}
            mode: 0755
      when: all or sgutil

    #validate
    - name: copying validate scripts
      copy:
        src: "../cli/validate/{{ item }}.sh"
        dest: "{{ cli_path }}/validate/{{ item }}"
        mode: "0755"
      when: all or validate
      loop:
        - coyote
        - docker
        - hip
        - iperf
        - mpi
        - vitis

    #copying workflows
    #coyote
    - name: copying coyote workflow
      block:
        - name: copying coyote workflow
          debug:
            msg: ""
        - name: new
          copy:
            src: "../cli/new/coyote.sh"
            dest: "{{ cli_path }}/new/coyote"
            mode: "0755"
        - name: build
          copy:
            src: "../cli/build/coyote.sh"
            dest: "{{ cli_path }}/build/coyote"
            mode: "0755"
        - name: program
          copy:
            src: "../cli/program/coyote.sh"
            dest: "{{ cli_path }}/program/coyote"
            mode: "0755"
        - name: run
          copy:
            src: "../cli/run/coyote.sh"
            dest: "{{ cli_path }}/run/coyote"
            mode: "0755"
      when: all or coyote
    #hip
    - name: copying hip workflow
      block:
        - name: copying hip workflow
          debug:
            msg: ""
        - name: new
          copy:
            src: "../cli/new/hip.sh"
            dest: "{{ cli_path }}/new/hip"
            mode: "0755"
        - name: build
          copy:
            src: "../cli/build/hip.sh"
            dest: "{{ cli_path }}/build/hip"
            mode: "0755"
        - name: run
          copy:
            src: "../cli/run/hip.sh"
            dest: "{{ cli_path }}/run/hip"
            mode: "0755"
      when: all or hip
    #mpi
    - name: copying mpi workflow
      block:
        - name: copying mpi workflow
          debug:
            msg: ""
        - name: new
          copy:
            src: "../cli/new/mpi.sh"
            dest: "{{ cli_path }}/new/mpi"
            mode: "0755"
        - name: build
          copy:
            src: "../cli/build/mpi.sh"
            dest: "{{ cli_path }}/build/mpi"
            mode: "0755"
        - name: run
          copy:
            src: "../cli/run/mpi.sh"
            dest: "{{ cli_path }}/run/mpi"
            mode: "0755"
      when: all or mpi
    #vitis
    - name: copying vitis workflow
      block:
        - name: copying vitis workflow
          debug:
            msg: ""
        - name: new
          copy:
            src: "../cli/new/vitis.sh"
            dest: "{{ cli_path }}/new/vitis"
            mode: "0755"
        - name: build
          copy:
            src: "../cli/build/vitis.sh"
            dest: "{{ cli_path }}/build/vitis"
            mode: "0755"
        - name: program
          copy:
            src: "../cli/program/vitis.sh"
            dest: "{{ cli_path }}/program/vitis"
            mode: "0755"
        - name: run
          copy:
            src: "../cli/run/vitis.sh"
            dest: "{{ cli_path }}/run/vitis"
            mode: "0755"
      when: all or vitis