---

- hosts: 
    #- hacc-build
    #- alveo-u250
    #- alveo-u280
    #- alveo-u50d
    #- alveo-u55c
    #- versal-vck5000
    #- hacc-boxes
    #- alveo-u55c-01.inf.ethz.ch
    - hacc-box-01.inf.ethz.ch
  become: true
  become_method: community.general.sudosu
  become_user: root
  ignore_unreachable: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    #paths definition
    sgrt_base_path: /opt/sgrt #/opt/sgrt
    cli_path: "{{ sgrt_base_path }}/cli"
    cli_name: sgutil
    #installation control (all means we attempt to create and copy all directories, files, and scripts)
    all: false
    #scripts
    build: false
    common: false
    enable: false
    examine: false
    get: false
    new: false
    program: false
    reboot: false
    run: false
    set: false
    sgutil: false
    templates: false
    validate: false
    #workflows
    coyote: true
    hip: false
    mpi: true
    vitis: false
  tasks:

    #creating directories
    - name: creating directories
      file:
        path: "{{ item }}"
        state: directory
      when: all
      loop:
        - "{{ sgrt_base_path }}"
        - "{{ sgrt_base_path }}/build"
        - "{{ sgrt_base_path }}/common"
        - "{{ sgrt_base_path }}/constants"
        - "{{ sgrt_base_path }}/enable"
        - "{{ sgrt_base_path }}/get"
        - "{{ sgrt_base_path }}/new"
        - "{{ sgrt_base_path }}/program"
        - "{{ sgrt_base_path }}/run"
        - "{{ sgrt_base_path }}/set"
        - "{{ sgrt_base_path }}/templates"
        - "{{ sgrt_base_path }}/validate"

    #copying files (when all/only if they do not exist on the remote)
    #constants
    - name: checking constants
      find:
        paths: "{{ sgrt_base_path }}/constants"
        recurse: no
      register: constants_contents
      when: all
    - name: copying constants (if folder is empty)
      copy:
        src: "../cli/constants/{{ item }}"
        dest: "{{ sgrt_base_path }}/constants/{{ item }}"
        mode: "0644"
      when: all and constants_contents.matched == 0
      loop:
        - ACAP_SERVERS_LIST
        - CPU_SERVERS_LIST
        - FPGA_SERVERS_LIST
        - GPU_SERVERS_LIST
        - LOCAL_PATH
        - MPICH_PATH
        - MY_PROJECTS_PATH
        - ROCM_PATH  
        - VIRTUALIZED_SERVERS_LIST
        - VIVADO_DEVICES_MAX
        - XILINX_PLATFORMS_PATH
        - XILINX_TOOLS_PATH
        - XRT_PATH
    #devices
    #devices_acap_fpga
    - name: checking devices_acap_fpga
      stat:
        path: "{{ sgrt_base_path }}/devices_acap_fpga"
      register: devices_acap_fpga_stat
      when: all
    - name: copying devices_acap_fpga 
      copy:
        src: "../cli/devices_acap_fpga"
        dest: "{{ sgrt_base_path }}/devices_acap_fpga"
        mode: "0644"
      when: all and not devices_acap_fpga_stat.stat.exists
    #devices_gpu
    - name: checking devices_gpu
      stat:
        path: "{{ sgrt_base_path }}/devices_gpu"
      register: devices_gpu_stat
      when: all
    - name: copying devices_gpu 
      copy:
        src: "../cli/devices_gpu"
        dest: "{{ sgrt_base_path }}/devices_gpu"
        mode: "0644"
      when: all and not devices_gpu_stat.stat.exists
    #version
    - name: checking version
      stat:
        path: "{{ sgrt_base_path }}/VERSION"
      register: version_stat
      when: all
    - name: copying version
      copy:
        src: "../cli/VERSION"
        dest: "{{ sgrt_base_path }}/VERSION"
        mode: "0644"
      when: all and not version_stat.stat.exists

    #copying templates
    #coyote
    - name: deleting coyote template
      file:
        path: "{{ sgrt_base_path }}/templates/coyote"
        state: absent
      register: coyote_templates
      when: all or (templates and coyote)
    - name: copying coyote template
      copy:
        src: "../cli/templates/coyote"
        dest: "{{ sgrt_base_path }}/templates"
        mode: "0755"
      when: coyote_templates.changed
    #hip
    - name: deleting hip template
      file:
        path: "{{ sgrt_base_path }}/templates/hip"
        state: absent
      register: hip_templates
      when: all or (templates and hip)
    - name: copying hip template
      copy:
        src: "../cli/templates/hip"
        dest: "{{ sgrt_base_path }}/templates"
        mode: "0755"
      when: hip_templates.changed
    #mpi
    - name: deleting mpi template
      file:
        path: "{{ sgrt_base_path }}/templates/mpi"
        state: absent
      register: mpi_templates
      when: all or (templates and mpi)
    - name: copying mpi template
      copy:
        src: "../cli/templates/mpi"
        dest: "{{ sgrt_base_path }}/templates"
        mode: "0755"
      when: mpi_templates.changed
    #vitis  
    - name: deleting vitis template
      file:
        path: "{{ sgrt_base_path }}/templates/vitis"
        state: absent
      register: vitis_templates
      when: all or (templates and vitis)
    - name: copying vitis template
      copy:
        src: "../cli/templates/vitis"
        dest: "{{ sgrt_base_path }}/templates"
        mode: "0755"
      when: vitis_templates.changed

    #copying scripts 
    #build
    - name: copying build scripts
      copy:
        src: "../cli/build/{{ item }}.sh"
        dest: "{{ sgrt_base_path }}/build/{{ item }}"
        mode: "0755"
      when: all or build
      loop:
        - coyote
        - hip
        - mpi
        - vitis
    #common
    - name: copying common scripts
      copy:
        src: "../cli/common/{{ item }}.sh"
        dest: "{{ sgrt_base_path }}/common/{{ item }}"
        mode: "0755"
      when: all or common
      loop:
        - bitstream_dialog_check
        - deployment_dialog
        - deployment_dialog_check
        - device_dialog
        - device_dialog_check
        - device_dialog_gpu
        - device_list_check
        - driver_dialog_check
        - get_booking_system_db_passwd
        - get_booking_system_db_user
        - get_booking_system_host
        - get_booking_system_servers_list
        - get_constant
        - get_email
        - get_files
        - get_multiple_devices
        - get_servers
        - get_vivado_devices
        - is_acap
        - is_cpu
        - is_fpga
        - is_gpu
        - is_member
        - is_virtualized
        - platform_dialog
        - platform_dialog_check
        - project_dialog
        - project_dialog_check
        - ssh_key_add
        - target_dialog
        - target_dialog_check
        - version_dialog
        - version_dialog_check
    #enable
    - name: copying enable scripts
      copy:
        src: "../cli/enable/{{ item }}.sh"
        dest: "{{ sgrt_base_path }}/enable/{{ item }}"
        mode: "0755"
      when: all or enable
      loop:
        - vitis
        - vivado
        - xrt
    #examine
    - name: copying examine
      copy:
        src: "../cli/examine.sh"
        dest: "{{ sgrt_base_path }}/examine"
        mode: "0755"
      when: all or examine
    #get
    - name: copying get scripts
      copy:
        src: "../cli/get/{{ item }}.sh"
        dest: "{{ sgrt_base_path }}/get/{{ item }}"
        mode: "0755"
      when: all or get
      loop:
        - bdf
        - bus 
        - get_fpga_device_param
        - get_gpu_device_param
        - ifconfig
        - name
        - network
        - platform
        - serial
        - workflow
    #new
    - name: copying new scripts
      copy:
        src: "../cli/new/{{ item }}.sh"
        dest: "{{ sgrt_base_path }}/new/{{ item }}"
        mode: "0755"
      when: all or new
      loop:
        - coyote
        - hip
        - mpi
        - vitis
    #program
    - name: copying program scripts
      copy:
        src: "../cli/program/{{ item }}.sh"
        dest: "{{ sgrt_base_path }}/program/{{ item }}"
        mode: "0755"
      when: all or program
      loop:
        - coyote
        - enable_N_REGIONS
        - enable_regions
        - fpga_chmod
        - pci_hot_plug
        - reset
        - revert
        - vitis
        - vivado
    - name: copying program tcl
      copy:
        src: "../cli/program/{{ item }}"
        dest: "{{ sgrt_base_path }}/program/{{ item }}"
        mode: "0755"
      when: all or program
      loop:
        - flash_bitstream.tcl
        - flash_xrt_bitstream.tcl
    #reboot
    - name: copying reboot
      copy:
        src: "../cli/reboot.sh"
        dest: "{{ sgrt_base_path }}/reboot"
        mode: "0755"
      when: all or reboot
    #run
    - name: copying run scripts
      copy:
        src: "../cli/run/{{ item }}.sh"
        dest: "{{ sgrt_base_path }}/run/{{ item }}"
        mode: "0755"
      when: all or run
      loop:
        - coyote
        - hip
        - mpi
        - vitis
    #set
    - name: copying set scripts
      copy:
        src: "../cli/set/{{ item }}.sh"
        dest: "{{ sgrt_base_path }}/set/{{ item }}"
        mode: "0755"
      when: all or set
      loop:
        - gh
        - keys
    #sgutil
    - name: copying sgutil
      copy:
        src: "../cli/{{ cli_name }}.sh"
        dest: "{{ sgrt_base_path }}/{{ cli_name }}"
        mode: 0755
      register: sgutil_copy
      when: all or sgutil
    - name: copying sgutil_completion
      copy:
        src: "../cli/{{ cli_name }}_completion.sh"
        dest: /usr/share/bash-completion/completions/{{ cli_name }}
        mode: 0755
      when: sgutil_copy.changed
    #validate
    - name: copying validate scripts
      copy:
        src: "../cli/validate/{{ item }}.sh"
        dest: "{{ sgrt_base_path }}/validate/{{ item }}"
        mode: "0755"
      when: all or validate
      loop:
        - coyote
        - hip
        - iperf
        - mpi
        - vitis

    #copying workflows
    #coyote
    - name: copying coyote workflow
      block:
        - name: copying coyote workflow
          debug:
            msg: ""
        - name: new
          copy:
            src: "../cli/new/coyote.sh"
            dest: "{{ sgrt_base_path }}/new/coyote"
            mode: "0755"
        - name: build
          copy:
            src: "../cli/build/coyote.sh"
            dest: "{{ sgrt_base_path }}/build/coyote"
            mode: "0755"
        - name: program
          copy:
            src: "../cli/program/coyote.sh"
            dest: "{{ sgrt_base_path }}/program/coyote"
            mode: "0755"
        - name: run
          copy:
            src: "../cli/run/coyote.sh"
            dest: "{{ sgrt_base_path }}/run/coyote"
            mode: "0755"
      when: all or coyote
    #hip
    - name: copying hip workflow
      block:
        - name: copying hip workflow
          debug:
            msg: ""
        - name: new
          copy:
            src: "../cli/new/hip.sh"
            dest: "{{ sgrt_base_path }}/new/hip"
            mode: "0755"
        - name: build
          copy:
            src: "../cli/build/hip.sh"
            dest: "{{ sgrt_base_path }}/build/hip"
            mode: "0755"
        - name: run
          copy:
            src: "../cli/run/hip.sh"
            dest: "{{ sgrt_base_path }}/run/hip"
            mode: "0755"
      when: all or hip
    #mpi
    - name: copying mpi workflow
      block:
        - name: copying mpi workflow
          debug:
            msg: ""
        - name: new
          copy:
            src: "../cli/new/mpi.sh"
            dest: "{{ sgrt_base_path }}/new/mpi"
            mode: "0755"
        - name: build
          copy:
            src: "../cli/build/mpi.sh"
            dest: "{{ sgrt_base_path }}/build/mpi"
            mode: "0755"
        - name: run
          copy:
            src: "../cli/run/mpi.sh"
            dest: "{{ sgrt_base_path }}/run/mpi"
            mode: "0755"
      when: all or mpi
    #vitis
    - name: copying vitis workflow
      block:
        - name: copying vitis workflow
          debug:
            msg: ""
        - name: new
          copy:
            src: "../cli/new/vitis.sh"
            dest: "{{ sgrt_base_path }}/new/vitis"
            mode: "0755"
        - name: build
          copy:
            src: "../cli/build/vitis.sh"
            dest: "{{ sgrt_base_path }}/build/vitis"
            mode: "0755"
        - name: program
          copy:
            src: "../cli/program/vitis.sh"
            dest: "{{ sgrt_base_path }}/program/vitis"
            mode: "0755"
        - name: run
          copy:
            src: "../cli/run/vitis.sh"
            dest: "{{ sgrt_base_path }}/run/vitis"
            mode: "0755"
      when: all or vitis

    #copying to profile.d
    - name: add to system-wide $PATH.
      copy:
        dest: "/etc/profile.d/{{ cli_name }}.sh" #cli.sh
        content: 'PATH=$PATH:{{ sgrt_base_path }}'
      when: all