---

- hosts: 
    #- hacc-build
    #- alveo-u250
    #- alveo-u280
    #- alveo-u50d
    #- alveo-u55c
    #- versal-vck5000
    #- hacc-boxes
    - alveo-u55c-03.inf.ethz.ch
    #- hacc-box-01.inf.ethz.ch
  become: true
  become_method: community.general.sudosu
  become_user: root
  ignore_unreachable: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    #paths definition
    sgrt_base_path: /opt/sgrt #/opt/sgrt
    api_path: "{{ sgrt_base_path }}/api"
    cli_path: "{{ sgrt_base_path }}/cli"
    cli_name: sgutil
  tasks:

    - name: Execute update command with necessary environment settings
      shell: echo y | /opt/sgrt/update
      environment:
        http_proxy: http://proxy.ethz.ch:3128
        https_proxy: https://proxy.ethz.ch:3128
      become: true
      become_method: sudo
      become_user: root
      register: sgutil_output

    - name: Display full output of the update command
      debug:
        msg:
          - "Standard Output: {{ sgutil_output.stdout }}"
          - "Standard Error: {{ sgutil_output.stderr }}"
          - "Return Code: {{ sgutil_output.rc }}"